repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=79"
          - "--max-complexity=18"
          - "--ignore=E501,W503,E203,F401,D400,D101,D102,C101,F403,D205,D401,D202,T001,D105,D104,C901,D200,S001,D103,F841"
          - "--exclude=data/ docs/ test/"
        additional_dependencies:
          [
              "flake8-bugbear",
              "flake8-coding",
              "flake8-comprehensions",
              "flake8-debugger",
              "flake8-deprecated",
              "flake8-pep3101",
              "flake8-polyfill",
              "flake8-print",
              "flake8-string-format",
              "flake8-docstrings",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: forbid-new-submodules
      - id: pretty-format-json
        args: [ '--no-sort-keys' ]
      - id: no-commit-to-branch
        args: [ --branch, master ]
      - id: no-commit-to-branch
        args: [ --branch, main ]
