name: Continuous Integration for development

on: pull_request
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install lint dependencies
        run: |
          pip install pre-commit black
      - name: Install and run pre-commit
        uses: pre-commit/action@v3.0.1
  test:
    runs-on: ubuntu-22.04
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up testing python ${{ matrix.config.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.config.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
      - name: Setup a local virtual environment for caching
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Define a cache for the virtual environment based on the dependencies lock file to speed up later runs
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-root
      - name: Install coverage-badge
        run: pip install coverage-badge
      - name: Pytest
        env:
          ORS_API_KEY: ${{ secrets.ORS_API_KEY }}
        run: poetry run coverage run -m pytest -x
      - name: coverage badge
        run: coverage-badge -o coverage.svg
